name: PS4 Build with Sample

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout SDK
      uses: actions/checkout@v3
      with:
        repository: ps4-payload-dev/sdk
        path: sdk

    - name: Setup SDK
      working-directory: sdk
      run: |
        sudo apt update
        sudo apt install clang-18 lld-18
        # تثبيت الـ SDK في مجلد مؤقت وإضافته للمسار
        make DESTDIR=${{ runner.tool_cache }}/ps4-payload-sdk clean install
        echo "PS4_PAYLOAD_SDK=${{ runner.tool_cache }}/ps4-payload-sdk" >> $GITHUB_ENV

    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Build Main Payload (gdbsrv)
      run: |
        make -f Makefile.ps4 clean all

    # الخطوة الجديدة لبناء الـ Sample
    - name: Build Sample Payload
      working-directory: sample
      run: |
        make -f Makefile.ps4 clean all

    - name: Upload All Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PS4-GDB-Project
        path: |
          gdbsrv-ps4.elf
          sample/payload-ps4.elf
        if-no-files-found: error

  release:
    needs: build
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: PS4-GDB-Project
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true
          files: |
            gdbsrv-ps4.elf
            payload-ps4.elf
